[package]
name = "juegodelgato"
version = "1.6.9"
edition = "2021"


[dependencies]
bevy = "0.11.2"

[dependecies.bevy]
version = "0.11.2"
default-features = false
features = [
    "bevy_asset",
    "bevy_sprite",
    "png",
]